[project]
dependencies = [
    "apple @ https://github.com/mtalarico/test-no-deps",
    "banana @ https://github.com/mtalarico/test-direct-dep",
]
name = "carrot"
version = "0.1.0"
description = "a as in apple"
readme = "README.md"
requires-python = ">=3.10"
